theme: jekyll-theme-minimal
title: Farss's homepage
description: I haven’t decided yet!

plugins:
  - jekyll-optional-front-matter
  - jekyll-relative-links
  - jekyll-default-layout

optional_front_matter:
  remove_originals: true

relative_links:
  enabled: true
  collections: true

defaults:
  - scope:
      path: "mikrotik"
    values:
      layout: default
